---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    name: redis
  - port: 16379
    name: cluster
  clusterIP: None
  selector:
    app: redis
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: "redis"
  replicas: 6
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: registry.cn-hangzhou.aliyuncs.com/junv/cluster-redis:latest
        ports:
        - containerPort: 6379
          name: redis
          protocol: "TCP"
        - containerPort: 16379
          name: cluster
          protocol: "TCP"
        command:
          - "/usr/local/bin/redis-server"
        args:
          - "/root/redis.conf"
